### ISSUE TITLE
4.4.0-15 Kernel, problems with screen brightness

### ISSUE THREAD

**Issue by emersons** [milikhin/z3735-linux-patches#1]
Hi,

First of all, thanks for all the hard work. I am using the 4.4.0-15 patched kernel and am able to use the hadess wifi driver without it freezing my system. However, I am unable to change my screen brightness now.

In the stock kernel (4.4.0-21) this works fine, the brightness indicator shows a decrease and this is registered in /sys/class/backlight/intel_backlight/actual_brightness. In this kernel the indicator shows a change, but it fails to change the actual_brightness file and thus the screen brightness does not change.

Is this something related to the various kernel patches? Thanks

Edit. I should add I am running Ubuntu 16.04, amd64 on a z3735 laptop.

**Comment by milikhin** [comment]
Could you try 4.4.0-2 from Google Drive, please?
It has only patches for rtl8723bs and no patches related to brightness.

I'll also upload 4.6 that shoud work fine in coming days

**Comment by emersons** [comment]
Ok it works with that kernel. I have a bigger problem now though :(

Do you have any issues with the system freezing on your device? My computer crashes in less than an hour in the 4.4.0-15 kernel, but it also happens in the official 4.4.0-21 kernel so this has nothing to do with what you've done. This happens even if I have nothing else installed so it is an inherent problem with my device and the kernel.

I will try your 4.6 kernel when you release it. Perhaps they fixed this in the latest version?

**Comment by milikhin** [comment]
> My computer crashes in less than an hour in the 4.4.0-15 kernel

I believe it happens because of problems with C-States. I solved it on my tablet by setting Max C-State = 1 in BIOS, but you can also set the corresponding kernel parameter instead.

I think there is no C-State's problem in 4.6-rc1 kernel at Google Drive (some additional patches were applied, **4.6-rc1** directory)

**Comment by emersons** [comment]
Yeah I had read that, seems to be an ongoing bug. I am using your 4.4.6 kernel now, am up to 3 hours run time, usually it won't last an hour. Wifi is working and no issues with the brightness control. Thanks for uploading it man.

**Comment by milikhin** [comment]
Thank you, your feedback is very appreciated

**Comment by emersons** [comment]
Out of curiosity, do you have [this](http://imgur.com/MS3lBc9) problem? Before I run the axpd.sh script I have a false battery which is always at 100%, when I run the script my battery charge is reported correctly in the terminal but the fake battery (shown in orange) does not go away.

I asked icenowy if he had this problem, [he said he didn't](https://github.com/Icenowy/axpd/issues/2). He is no longer working on this now.

**Comment by milikhin** [comment]
> Out of curiosity, do you have this problem?

Yes. I believe that's because of the line `rmmod battery` in Icenowy's code. I think the command was used to unload unsupported kernel module and correspondent battery icon, but I don't have such module (`battery`) loaded on my tablet, so the icon is not removed.

The problem here is that I don't know which module we have to unload instead of `battery` to remove unsupported battery icon.

**Comment by Icenowy** [comment]
@milikhin @emersons CONFIG_ACPI_BATTERY=m

@emersons Please use "she" :-)

**Comment by milikhin** [comment]
@Icenowy Thank you :-)

Then, i'll upload new kernel with ```CONFIG_ACPI_BATTERY=m``` once 4.7 is released

**Comment by emersons** [comment]
@Icenowy  :D :D 

Thanks for the hard work you two!
